#!/bin/sh

NOOSS=0

if [[ -z "${OSS_BUCKET}" ]]; then
    echo OSS_BUCKET is empty.
    NOOSS=1
fi

if [[ -z "${OSS_DIST}" ]]; then
    echo OSS_DIST is empty.
    NOOSS=1
fi

if [[ -z "${OSS_KEY}" ]]; then
    echo OSS_KEY is empty.
    NOOSS=1
fi

if [[ -z "${OSS_SECRET}" ]]; then
    echo OSS_SECRET is empty.
    NOOSS=1
fi

if [[ -z "${OSS_REGION}" ]]; then
    echo OSS_REGION is empty.
    NOOSS=1
fi

if [[ ${NOOSS} == 0 ]]; then
    echo "${OSS_BUCKET}:${OSS_KEY}:${OSS_SECRET}" >/etc/passwd-ossfs
    chmod 640 /etc/passwd-ossfs
    mkdir -p ${OSS_DIST}
    /usr/bin/ossfs ${OSS_BUCKET} ${OSS_DIST} -ourl=http://oss-${OSS_REGION}.aliyuncs.com
fi

$*
